// src/app/api/collaboration/heartbeat/route.ts
import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function POST(req: NextRequest) {
    try {
        const body = await req.json();
        const { token, vendorEmail, level, displayName } = body;

        if (!token || !vendorEmail || level === undefined) {
            return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
        }

        // Upsert DocumentSession stringified as token_email
        const sessionId = `${token}_${Buffer.from(vendorEmail).toString('base64').substring(0, 20)}`;

        await prisma.documentSession.upsert({
            where: { id: sessionId }, // We'll assume id can be manually set, but wait id is autogenerated cuid
            update: {
                lastSeenAt: new Date(),
                level: Number(level),
                displayName: displayName || vendorEmail.split('@')[0],
            },
            create: {
                id: sessionId,
                token,
                fileId: 'N/A', // fileId is required by schema, but token is actually what binds the session
                userId: vendorEmail, // Keep track of email here
                level: Number(level),
                displayName: displayName || vendorEmail.split('@')[0],
                lastSeenAt: new Date(),
            }
        });

        return NextResponse.json({ success: true });
    } catch (error) {
        console.error('Heartbeat Error:', error);
        return NextResponse.json({ error: 'Failed to update heartbeat' }, { status: 500 });
    }
}
